### ISSUE TITLE
Column name "value" causes syntax error

### ISSUE THREAD

**Issue by aarongodin** [genjidb/genji#483] opened 2022-11-06 02:49 UTC
### What version of Genji are you using?

```
0.15.1
```

### What did you do?

First, I created a table with no schema:

```sql
CREATE TABLE IF NOT EXISTS settings
```

Then I tried to query the table:

```go
res, err := db.Query(`SELECT name, value FROM settings`)
```

### What did you expect to see?

Given I had not populated any rows, an empty result set.

### What did you see instead?

parsing error:

```
found VALUE, expected  at line 1, char 14
```

Given I change the column name in the select to `val` it works. This is what makes me think it's an issue with the parser. I believe the error returned could be improved as well. It looks like the expected value passed to the message cannot render as string.

**Comment by Darkclainer** [comment] 2023-08-06 17:15
Looking into code this indeed behavior of parser, but you can use keyword as column names with \` char:

```
CREATE TABLE settings ( name INT, `value` INT);
INSERT INTO settings(name, `value`) VALUES (1,2);
SELECT name, `value` FROM settings;
```

**Comment by asdine** [comment] 2023-11-26 18:55
Closing, as this is not a bug. @Darkclainer's answer is the right solution

**Closed by asdine** 2023-11-26 18:55 UTC
Labels: bug
